/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    eclipse
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://repo.spring.io/snapshot")
    }

    maven {
        url = uri("https://repo.spring.io/milestone")
    }
}

dependencies {
    implementation(libs.org.springframework.boot.spring.boot.starter.actuator)
    implementation(libs.de.codecentric.spring.boot.admin.starter.client)
    implementation(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    implementation(libs.org.springframework.boot.spring.boot.starter.security)
    implementation(libs.org.springframework.boot.spring.boot.starter.web)
    implementation(libs.org.springframework.boot.spring.boot.starter.webflux)
    implementation(libs.org.springframework.cloud.spring.cloud.starter.netflix.eureka.client)
    implementation(libs.org.springframework.cloud.spring.cloud.starter.config)
    implementation(libs.io.jsonwebtoken.jjwt.api)
    implementation(libs.org.springframework.kafka.spring.kafka)
    implementation(libs.org.postgresql.postgresql)
    implementation(libs.org.projectlombok.lombok)
    implementation(libs.org.springdoc.springdoc.openapi.starter.webmvc.ui)
    implementation(libs.org.springframework.cloud.spring.cloud.starter.bootstrap)
    runtimeOnly(libs.io.jsonwebtoken.jjwt.impl)
    runtimeOnly(libs.io.jsonwebtoken.jjwt.jackson)
    runtimeOnly(libs.org.springframework.boot.spring.boot.devtools)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.springframework.kafka.spring.kafka.test)
    testImplementation(libs.org.springframework.security.spring.security.test)
}

group = "uk.thisjowi"
version = "0.0.1-SNAPSHOT"
description = "Password"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
